config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'static_pages/about'
  get 'static_pages/contact'

  resources :posts
  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
      @post = Post.find(params[:id])
      if @post.user.nil? || current_user.id != @post.user.id
          respond_to do |format|
            format.html { redirect_to posts_url, alert: "You don't have permissions to edit this post." }
            format.json { head :no_content }
          end
      end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title JesuaRorblog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Jesua ROR BLog', posts_path, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Home', posts_path
            %li= link_to 'About', static_pages_about_path
            %li= link_to 'Contact', static_pages_contact_path
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to t('navbar.logout'), destroy_user_session_path, method: :delete
            - else
              %li
                = link_to t('navbar.signin'), new_user_session_path
              %li
                = link_to t('navbar.signup'), new_user_registration_path
    .body
      .container
        - if notice
          %p.bg-success= notice
        - if alert
          %p.bg-danger= alert
      .container
        = yield

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.hidden_field :user_id, class: 'form-control', value: current_user.id
  .field
    = f.label :title
    %br/
    = f.text_field :title, class: 'form-control'
  .field
    = f.label :content
    %br/
    = f.text_area :content, class: 'form-control'
  .actions
    = f.submit class: 'btn btn-success btn-block'

app/views/posts/edit.html.haml
%h1 Editing Post

= render 'form'

= link_to 'Show', @post, class: 'btn btn-lg btn-warning'
= link_to 'Back', posts_path, class: 'btn btn-lg btn-danger'

app/views/posts/index.html.haml
.row
  .col-xs-12.col-md-4.text-center
    =render template: 'static_pages/about'
  .col-xs-12.col-md-8
    %h1.text-center Leave a comment!
    %table.table.datatable
      %thead
        %tr
          %th.text-center.hidden-xs Name
          %th.text-center Title
          %th.text-center.hidden-xs Content
          %th.text-center Actions
          //%th.text-center{:colspan => "3"} Actions
      %tbody.text-center
        - @posts.each do |post|
          %tr
            %td.hidden-xs= post.user.nil? ? "Anonymous" : post.user.name
            %td= post.title
            %td.hidden-xs= post.content
            %td
              = link_to '', post, class: 'btn btn-warning fa fa-2x fa-eye', title: 'Show'
              -if !post.user.nil? && post.user.id == current_user.id
                = link_to '', edit_post_path(post), class: 'btn btn-primary fa fa-2x fa-edit', title: 'Edit'
                = link_to '', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger fa fa-2x fa-close', title: 'Destroy'
    %br/
    = link_to 'New Post', new_post_path, class: 'btn btn-success btn-lg btn-block'

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

= link_to 'Back', posts_path, class: 'btn btn-danger btn-lg'

app/views/posts/show.html.haml
%p.lead
  %strong Title
  = @post.title

%p.lead
  %strong Content:
  = @post.content

%p.lead
  %strong Author
  = @post.user.name

-if !@post.user.nil? && @post.user.id == current_user.id
  = link_to 'Edit', edit_post_path(@post), class: 'btn btn-lg btn-primary'

= link_to 'Back', posts_path, class: 'btn btn-lg btn-danger'

app/views/static_pages/about.html.haml
%h1 Jesua - ROR Blog
%p.lead Just another blog, based on Ruby on Rails
%span.fa.fa-5x.fa-diamond.red

app/views/static_pages/contact.html.haml
%h1 Contact
%p.lead
  %span{class: "fa fa-2x fa-github"}
  GitHub account
%a{class: "btn btn-success btn-large", href: "https://github.com/quesow"} Go!